title: Ben Cochez
feedTitle: Ben Cochez - Heavy Industrialized Feed
email: ben@heavyindustries.io
description:
baseurl: ""
url: "http://heavyindustries.io"
twitter_username: bencochez
github_username:  benc

markdown: kramdown

exclude:
  - tasks/
  - package.json
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
